# Generated by Django 6.0.7 on 2026-08-19 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='تصویر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در تاریخ')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'اخبار',
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='نام')),
                ('last_name', models.CharField(max_length=30, verbose_name='نام خانوادگی')),
                ('father_name', models.CharField(max_length=30, verbose_name='نام پدر')),
                ('birth_date', models.DateField(verbose_name='تاریخ تولد')),
                ('address', models.CharField(max_length=300, verbose_name='نشانی')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('email_address', models.EmailField(max_length=254, verbose_name='نشانی ایمیل')),
                ('has_medical_condition', models.BooleanField(verbose_name='دارای شرایط پزشکی')),
                ('describe_condition', models.TextField(verbose_name='شرح شرایط پزشکی')),
            ],
            options={
                'verbose_name': 'ثبت نام',
                'verbose_name_plural': 'ثبت نام',
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='نام')),
                ('last_name', models.CharField(max_length=30, verbose_name='نام خانوادگی')),
                ('birthdate', models.DateField(verbose_name='تاریخ تولد')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('specialization', models.CharField(choices=[('kickboxing', 'کیک بوکسینگ'), ('muaythai', 'موی تای'), ('boxing', 'بوکس'), ('fitness', 'فیتنس'), ('trx', 'تی آر ایکس'), ('crossfit', 'کراسفیت')], max_length=50, verbose_name='تخصص')),
                ('experience', models.PositiveSmallIntegerField(verbose_name='سابقه کاری(سال)')),
                ('biography', models.TextField(null=True, verbose_name='بیوگرافی')),
            ],
            options={
                'verbose_name': 'مربی',
                'verbose_name_plural': 'مربیان',
            },
        ),
        migrations.CreateModel(
            name='GymClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(choices=[('kickboxing', 'کیک بوکسینگ'), ('muaythai', 'موی تای'), ('boxing', 'بوکس'), ('fitness', 'فیتنس'), ('trx', 'تی آر ایکس'), ('crossfit', 'کراسفیت')], max_length=50)),
                ('capacity', models.PositiveSmallIntegerField(verbose_name='ظرفیت کلاس')),
                ('schedule', models.CharField(max_length=100, verbose_name='برنامه زمانی کلاس')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trainer')),
            ],
            options={
                'verbose_name': 'کلاس',
                'verbose_name_plural': 'کلاس\u200cها',
            },
        ),
    ]
