# Generated by Django 6.0.7 on 2026-07-27 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('father_name', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('address', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=11)),
                ('email_address', models.EmailField(max_length=254)),
                ('has_medical_condition', models.BooleanField()),
                ('describe_condition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('birthdate', models.DateTimeField()),
                ('phone_number', models.CharField(max_length=11)),
                ('specialization', models.CharField(max_length=50)),
                ('experience', models.CharField(verbose_name=50)),
                ('biography', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GymClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(choices=[('kickboxing', 'کیک بوکسینگ'), ('muaythai', 'موی تای'), ('boxing', 'بوکس'), ('fitness', 'فیتنس'), ('trx', 'تی آر ایکس'), ('crossfit', 'کراسفیت')], max_length=50)),
                ('capacity', models.PositiveSmallIntegerField()),
                ('schedule', models.CharField(max_length=100)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trainer')),
            ],
        ),
    ]
